/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'welcome',
      label: '📄 Home',
    },
    {
      type: 'category',
      label: 'Apps',
      link: {
        type: 'generated-index',
        title: 'Apps',
        description:
          "Explore Documentation for Comp Labs Apps! Handmade by Comp Labs for Android, iOS, Windows, macOS, Linux Desktop, and Web. Select one of the document below to start!",
        // keywords: ['guides'],
        // image: '/img/complabs.png',
      },
      items: [
        {
          type: 'doc',
          id: 'apps/apple-store/applestore',
        },
        {
          type: 'doc',
          id: 'apps/google-docs/gdocs',
        },
        {
          type: 'doc',
          id: 'apps/gadget-compare/gadgetcompare',
        },
        {
          type: 'doc',
          id: 'apps/cloud-console/cloudconsole',
        },
      ],
    },
    {
      type: 'category',
      label: 'Comp Labs Meet',
      link: {
        type: 'generated-index',
        title: 'Apps',
        description:
          "Explore Official Documentation for Comp Labs Meet. Easy to Understand! Select one of the document below to start!",
        // keywords: ['guides'],
        // image: '/img/complabs.png',
      },
      items: [
        {
          type: 'doc',
          id: 'comp-labs-meet/clmeet',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        {
          type: 'doc',
          id: 'tutorial-basics/createpage',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/create-a-document',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/create-a-blog-post',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/markdown-features',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/deploy-your-site',
        },
        {
          type: 'doc',
          id: 'tutorial-basics/congratulations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [
        {
          type: 'doc',
          id: 'tutorial-extras/manage-docs-versions',
        },
        {
          type: 'doc',
          id: 'tutorial-extras/translate-your-site',
        },
      ],
    },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
  ],
};
// module.exports = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };
