blank_issues_enabled: true

contact_links:
  - name: Get Help / Ask General Questions in GitHub Discussions
    url: https://github.com/Comp-Labs/comp-labs-website/discussions
    about: Have a question? Need Help? Feel Free to ask in the GitHub Discussions Platform.