name: 📦 Feature Request
description: Came up with an idea? Feel free to share it here.
title: "[Feature]: "
labels: ["feature-request", "enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the enhancement is, and why you consider it to be a enhancement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is it related to a Issue?
      description: Is your feature request related to a problem you are facing? Please describe the problem you are trying to solve.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Alternative Solutions/Features
      description: Describe alternatives you've considered. Please describe alternative solutions or features you have considered.
    validations:
        required: true
  - type: dropdown
    id: version
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!
      options:
        - "Yes"
        - "No"
        - Maybe
    validations:
      required: true