# This is a basic workflow that is manually triggered

name: Swizzle

on:
  workflow_dispatch:

jobs:
  swizzle:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Deps n Swizzle
      run: npm install && npm i --save disqus-react && npm run swizzle @docusaurus/theme-classic BlogPostItem -- --wrap --danger && git config --global user.email "rudra_sen@outlook.com" && git config --global user.name "Rudra Sen" git commit -m "Swizzle Complete" && git push -u origin main
