name: 'DocSearch Crawler'

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
    - uses: actions/checkout@v2
    - uses: darrenjennings/algolia-docsearch-action@master
    with:
    algolia_application_id: '5BME7GVXKF'
    algolia_api_key: '25d03e7421fce25240ee86175434634d'
    file: 'docsearch/config.json'